# render.yaml
services:
  - type: web
    name: expense-tracker
    runtime: python
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: ./startup.sh
    envVars:
      - key: PORT
        value: 10000
      - key: RENDER
        value: true